# Generated by Django 5.2.8 on 2025-12-13 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='core.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'teacher_profile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.subject'),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['student', 'exam_type'], name='core_score_student_e5ef0b_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['subject', 'exam_type'], name='core_score_subject_c5a403_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'subject', 'exam_type')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='core_attend_date_801bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject', 'date'], name='core_attend_subject_04fbb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
