# Generated by Django 5.2.8 on 2025-12-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects_taught',
        ),
    ]
