# Generated by Django 5.2.8 on 2025-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_teacher_subjects_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final'), ('assignment', 'Assignment'), ('attendance', 'Attendance Penalty')], max_length=20),
        ),
    ]
