# Generated by Django 5.2.8 on 2025-12-28 16:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AlterField(
            model_name='score',
            name='exam_type',
            field=models.CharField(choices=[('monthly', 'Monthly Test'), ('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final'), ('assignment', 'Assignment'), ('attendance', 'Attendance Penalty')], default='quiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['recorded_at'], name='core_score_recorde_c06292_idx'),
        ),
    ]
