# Generated by Django 5.2.8 on 2026-01-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_score_options_alter_score_exam_type_and_more'),
    ]

    operations = [
    ]
