# Generated by Django 5.2.8 on 2025-12-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_conversation_options_alter_conversation_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Chat', max_length=100),
        ),
    ]
