# Generated by Django 5.2.8 on 2025-12-20 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_teacher_subjects_taught'),
        ('timetable', '0003_alter_timetableentry_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.subject'),
        ),
    ]
