# Generated by Django 5.2.8 on 2025-12-20 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0003_alter_attendance_subject'),
        ('core', '0005_remove_teacher_subjects_taught'),
        ('timetable', '0004_alter_timetableentry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
