# Generated by Django 5.2.8 on 2025-12-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_score_subject_delete_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
