# Generated by Django 5.2.8 on 2025-12-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
